language: rust
dist: trusty
matrix:
  fast_finish: true
  include:
  - rust: stable-i686
    os: linux
    addons:
      apt:
        packages:
        - gcc-multilib
        - libssl-dev:i386
        - g++-multilib
        - apt-transport-https
before_install:
- cd $HOME && curl -Ls https://github.com/Southclaws/sampctl/releases/download/1.8.37/sampctl_1.8.37_linux_amd64.tar.gz
  -o ./bin/tmp.tar.gz
- cd bin && tar xzf tmp.tar.gz && rm tmp.tar.gz
- alias sampctl=$HOME/bin/sampctl
- cd $HOME/build/Sreyas-Sreelal/samp-bcrypt
script:
- make setup
- make release
- make run
deploy:
  on:
    all_branches: true
  provider: bintray
  file: bintray.json
  user: sreyas-sreelal
  key:
    secure: qWSpxdj2nSWnOCWG/5tAECED38iAYvRUMnBJfVBLAqWrZqPdBVtjL+Ja03DV1PMOgNW3XN2rJ/acSCQsOrIhPC4gwi2nu0lyvb5MuoaMyNXaoyhGsr/TId1r7ORk7wa025yZD/PsAtknb3xPWH0G9Qc95EnOI2JqKymP76xJeZeSBhvcMe5AgcIs7n7ki2lvUUSvIyF55Ce2JzxA64UaSejR6GSBrVI3dlq7W+t56PIhogWhs0k+WZuB78CWcwLF2+po85fKSycc/YWEjFJBNQ5Mc1OB980hLWJcQJfeM/JxAFJPMTfmk/Q8eA41XTULOSc42uxbF+9eljWGxrVwFdFjar2WafWDZbBEkW1hm10HsBx0+2nYhkt1mSRKsZ2sEr4Guls6U37PZLEIS5FioTU+ULBHgaen6FLuf/YHF3c75ao17suLWig1rhBazNqX6hZ/aD7IO4+8SZ0We7tbgLlJAm9KgU237XzAxVarv63mxZM4YFQIdMuwos1H2zL5kBREjXloywbLdeOzCdc/y1jUV3t948ox3uYIQCLxDUO/6rh0GnvGfZO+F0DIv/+Q3xNQQ581JL3DakEi6sjyBcJ+9b8BsBxkFrlVVl4hXNVeAvKjToUdSmUzunnZFXt8EAAaeiQaDy859F39SiSRJfPz9bMtVcyJ5QwTk0adyHk=
  skip_cleanup: true
