language: rust
dist: trusty

matrix:
  fast_finish: true
  include:
  - rust: nightly-i686
    os: linux
    addons:
      apt:
        packages:
        - gcc-multilib
        - libssl-dev:i386
        - g++-multilib
install:
- curl https://raw.githubusercontent.com/Southclaws/sampctl/master/install-deb.sh | sh


script:
- make setup
- make release
- make run

deploy:
  provider: releases
  api_key:
    secure: UDDrjbtiVAQ3ASLsoTNO97MFn0UUvIEeGF2zUM/n3J2v/hg4IxqXPSsneLrWFfLGqW5kONdNlKbDMwcKBGGCVl89SM+WzxpOmdestvu9FHDb+igkjhQQjtNvIkkbamVyiSxSRrg5DEXud2Z9orOWcE051PivElp5kfySuKpmGNz4YMc4gNHGj8t5vN7adtd5IYSGkY+vmXRbQr842VzdZNkcZ5MIZIosYWmHBkJY0pOuuqLuXzzicpFbBJCX6U0tt8LCEXeFKGcPUiseIrK8niw/iXAd5efF+WN2BJbfLKJTv3mihwiGECk/n+KdQR4mAHeMwrazshPxiljnMQf/kAascV34uBNkM+h+mjvbiksdWV9wpNcaXYomFlZtq/eq561TQsZyRHr6oDffMPoctg342P8KookVrPu5kovgISddvK+MPiQCL7fCgF5vv4OjHSmm4XwAeAZuHL4p0iXOuz2QVMleBIDqbAJAvs/ISD9P0Z/haHTgoVCLzP6crmN7GTmxKRlYkSJPq+GHBlX+kSR39P6bVrfxq581frjFB5HPr21M5DlSuqCaiLTOnmFCg/5KrwzASEWXZ7Av9BFLXsP78bqu2uxKbre0MCb2NFZN2g+eFbMVyDWxHxhrSIWgv8qXMtgFKIdHYu/4oR2RoIF4myPVwWYKydBvYozcXJk=
  file: target/release/libsamp_bcrypt.so
  skip_cleanup: true
  draft: true
  on:
    repo: Sreyas-Sreelal/samp-bcrypt
