[package]
name = "samp-bcrypt"
version = "0.1.0"
authors = ["Sreyas <Sreyassreelal@gmail.com>"]

[lib]
name = "samp_bcrypt"
crate-type = ["cdylib"]

[dependencies]
samp-sdk = {git = "https://github.com/ZOTTCE/samp-sdk"}
bcrypt = "0.2.1"